# for format details, see https://docs.github.com/actions

name: Pytest summary
author: Dario Curreri
description: Run tests and display summary

inputs:
  path:
    description: Path to folder containing tests
    required: true
    default: tests

runs:
  using: composite
  steps:

    - run: pip install pytest
      shell: bash

    - run: pytest --junit-xml=.test_report.xml ${{ inputs.path }}
      shell: bash

    - uses: test-summary/action@v1
      with:
        paths: .test_report.xml
      if: always()