# for format details, see https://docs.github.com/actions

name: Hello World

on:
  workflow_call:
    inputs:
      who-to-greet:
        description: Who to greet
        required: true
        type: string
  workflow_dispatch:
    inputs:
      who-to-greet:
        description: Who to greet
        required: true
        type: string

jobs:
  greet:
    runs-on: ubuntu-latest
    name: Greating
    steps:

      - uses: actions/checkout@main

      - id: greet
        uses: dariocurr/actions/hello-world@main
        with:
          who-to-greet: ${{ inputs.who-to-greet }}

      - run: echo status ${{ steps.greet.outputs.status }}
        shell: bash
