# for format details, see https://docs.github.com/actions

name: "[TEST] Validate Python"

on:
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: "3.9"

      - name: Run tests
        uses: dariocurr/actions/pytest-summary@main
        with:
          path: tests/python
          options: -vv -s
