# for format details, see https://docs.github.com/actions

name: Validate Python

on:
  workflow_call:
    inputs:
      path:
        description: Path to tests
        required: true
        type: string
        default: tests
  workflow_dispatch:
    inputs:
      path:
        description: Path to tests
        required: true
        type: string
        default: tests

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: "3.9"

      - name: Install Pytest
        run: pip install pytest pytest-md-report

      - name: Run tests
        run: pytest ${{ inputs.path }}

      - name: Create test summary
        uses: test-summary/action@v1
        with:
          paths: .test_report.xml
        if: always()
