# for format details, see https://docs.github.com/actions

name: Validate `Dockerfile`

on:
  workflow_call:
    inputs:
      dockerfile:
        description: Path to `Dockerfile`
        required: true
        type: string
      merge:
        description: Whether to merge after validation
        required: false
        type: boolean
        default: false
      from:
        description: Origin branch
        required: false
        type: string
      to:
        description: Target branch
        required: false
        type: string

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Build Docker image
        uses: docker/build-push-action@master
        with:
          push: false
          context: ${{ inputs.dockerfile }}

  if: ${{ inputs.merge }}
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Merge `from` in `to` branch
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: ${{ inputs.from }}
          target_branch: ${{ inputs.to }}
          github_token: ${{ github.token }}
          message: Merging ${{ inputs.from }} into ${{ inputs.to }} using Github Actions
